version: 2
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"

  - directory: "/"
    package-ecosystem: "gitsubmodule"
    schedule:
      interval: "daily"

  - directory: "/tinyaudio-python"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
