[package]
name = "tinyaudio"
version = "0.1.0"
edition = "2021"

[dependencies]
miniaudio-sys = { path = "../miniaudio-sys" }
thiserror = "1.0"

[target.'cfg(windows)'.dependencies]
widestring = "1.0"

[dev-dependencies]
serial_test = "0.9"
